version: 2.1

executors:
  ruby:
    docker:
      - image: circleci/ruby

jobs:
  test:
    executor: ruby
    parallelism: 2
    steps:
      - checkout
      - run: gem install rspec
      - run: |
          TEST_FILES=$(circleci tests glob spec/**/*_spec.rb | circleci tests split)
          rspec --failure-exit-code=0 -- $TEST_FILES
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  test_again:
    executor: ruby
    steps:
      - attach_workspace:
          at: ~/project
      - run: gem install rspec
      - run: |
          head -2 spec/examples-0.txt > spec/examples.txt
          tail -qn +3 $(ls spec/examples-*.txt) >> spec/examples.txt
          mv spec/examples.txt spec/examples-0.txt
      - run: rspec --only-failures

workflows:
  test:
    jobs:
      - test
      - test_again:
          requires: [test]
